name: webscrollbar
description: A scrollbar that is designed for the desktop version of web. It creates a general scrollbar, for the desktop version of your website.
version: 0.0.1
homepage: https://gitlab.com/dezso15/webscrollbar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  smooth_scroll_web: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
